### ISSUE TITLE
Polymorphic arguments supported?

### ISSUE THREAD

**Issue by josephlbarnett** [ExpediaDotCom/graphql-kotlin#195]
I'm trying to define a query that accepts polymorphic arguments as input.

Here's what I have so far:

```kotlin
interface FilterDef {
    val field: String
}

data class StringRangeFilterDef(override val field: String, val min: String, val max: String) : FilterDef
data class IntRangeFilterDef(override val field: String, val min: Int, val max: Int) : FilterDef
data class StringValueFilterDef(override val field: String, val value: String) : FilterDef
data class IntValueFilterDef(override val field: String, val value: Int) : FilterDef
data class FilterList(val filters: List<FilterDef>)

class Query : GraphQLQueryResolver {
    fun queryObjects(filter: FilterList): Result {
        // calculate and return result
    }
}
```

When I try to load the generated schema in GraphiQL, it fails with a big red CDN-obfuscated javascript stacktrace.  If I change FilterList to contain a specific type of filter, eg `List<StringRangeFilterDef>`s, then the schema loads ok.  

The main difference I can see between the two is that with polymorphism, the Filter data types are `OBJECT`s, while without, the single StringRangeFilterDef is defined as an `INPUT_OBJECT` (and named "StringRangeFilterDefInput".

Is this a case that is currently supported, and I'm missing how to hook it up properly?  If not, is there a best practice workaround for what I'm trying to do?

**Comment by brennantaylor** [comment]
The graphql spec does not allow input types to inherit interfaces or be interfaces. So we can't really support it. It is annoying. I believe there is a proposal to allow it.

We could investigate providing a better error message though if we detect generated code trying to use an interface instead of bombing by producing a bad schema.

https://stackoverflow.com/questions/41921137/can-a-graphql-input-type-inherit-from-another-type-or-interface

**Comment by josephlbarnett** [comment]
Ok, thanks for the explanation!
