### ISSUE TITLE
Upgrade to graphql-java 13

### ISSUE THREAD

**Issue by smyrick** [ExpediaDotCom/graphql-kotlin#216]
**Is your feature request related to a problem? Please describe.**
`graphql-java` released v13.0 in June 2019. We should update to stay on top of releases.

https://www.graphql-java.com/

**Describe alternatives you've considered**
We are using an unsupported version 11. We could downgrade to the 9.X branch which has some long term support (LTS) but we should just stay on the latest until we get to another LTS release

**Additional context**
There were some breaking changes made that we will need to handle in our library

https://github.com/graphql-java/graphql-java/releases/tag/v12.0
https://github.com/graphql-java/graphql-java/releases/tag/v13.0

**Comment by rharriso** [comment]
It looks like `DirectiveWiringHelper` is depending on `SchemaGeneratorDirectiveHelper`, this class is marked as `@internal`, and is expecting an argument of type `SchemaGeneratorDirectiveHelper.Parameters` which is contained by a package private class. 

If it's not a required feature (I noticed in the wiki it was recommended), maybe it should be removed when upgrading `graphql-java`. Otherwise it will have to be refactored to rely only on the public API.

**Comment by rharriso** [comment]
I've got a branch open that's resolve some low hanging issues related to changes in apis used by tests:
 
https://github.com/rharriso/graphql-kotlin/commits/java-graphql-12

I haven't addressed the `FunctionBuilder` and `PropertyBuilder` which ... may require using the new `CodeRegistry`.

**Comment by rharriso** [comment]
@smyrick are you aware of any other work that's been done on this issue?

**Comment by dkuc84** [comment]
@rharriso we are currently blocked by https://github.com/graphql-java/graphql-java/pull/1560

**Comment by dkuc84** [comment]
WIP -> https://github.com/dkuc84/graphql-kotlin/tree/graphql_java_12

**Comment by rharriso** [comment]
Awesome, thanks.
