### ISSUE TITLE
Custom Scalar in InputType

### ISSUE THREAD

**Issue by vetm73** [ExpediaDotCom/graphql-kotlin#237]
Hi,

I have created a custom scalar for ZonedDateTime. This working fine for my queries. But in my mutatation I would like this class as my input and output types. 

Question:
Is it possible to use your data class with custom scalar for ZonedDateTime both as InputType and Type? When I create an identical data class where the ZonedDateTime is replaced by a String it works. But I would like to know what the best practice is because a almost equal data class seems 'wrong' to me.

The InputType receives the following json from the frontend:
```
"period":{"from":"2019-06-04T10:00:00.000Z","till":"2019-07-08T10:00:00.000Z"}
```

Explanation:
When using the data class pasted below as InputType it first is converted to a ZonedDateTime by the Coercing<ZonedDateTime, String> and then it gets deserialized again by jackson to create the object with the following error:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.ZonedDateTime` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: ee.seventythr.web.backend.domain.Project["period"]->ee.seventythr.web.backend.domain.Period["from"])
``` 
because the ZonedDateTime object is deserialized to 

```
{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"month":"JUNE","dayOfWeek":"TUESDAY","dayOfYear":162,"nano":0,"year":2019,"monthValue":6,"dayOfMonth":11,"hour":10,"minute":0,"second":0,"chronology":{"id":"ISO","calendarType":"iso8601"}}
```

```
data class Project(
    @Id
    @GraphQLID
    val id: String? = null,
    val name: String,
    val company: String,
    val description: String,
    val for_company: List<Image>? = emptyList(),
    val language: List<Image>? = emptyList(),
    val tools: List<Image>? = emptyList(),
    val period: Period,
    val display: Boolean? = true
)

data class Image(
    val name: String,
    val image: String?
)

data class Period(
        val from: ZonedDateTime,
        val till: ZonedDateTime
)
```

```
private objectDateCoercing : Coercing<ZonedDateTime, String> {
    override fun parseValue(input: Any?): ZonedDateTime = ZonedDateTime.parse(serialize(input), DateTimeFormatter.ISO_DATE_TIME) 

    override fun parseLiteral(input: Any?): ZonedDateTime? {
        val dateString = (input as? StringValue)?.value
        return ZonedDateTime.parse(dateString) 
    }

    override fun serialize(dataFetcherResult: Any?): String = dataFetcherResult.toString()
}
```

**Comment by vetm73** [comment]
I managed to 'solve' this with:

```
class CustomJsonDateDeserializer : JsonDeserializer<ZonedDateTime>() {
    @Throws(IOException::class, JsonProcessingException::class)
    override fun deserialize(jsonParser: JsonParser,
                    deserializationContext: DeserializationContext): ZonedDateTime {
        val node = jsonParser.readValueAsTree<JsonNode>()
        val zone = ZoneId.of(node.get("zone").get("id").asText())
        return ZonedDateTime.of(
            node.get("year").asInt(),
            node.get("monthValue").asInt(),
            node.get("dayOfMonth").asInt(),
            node.get("hour").asInt(),
            node.get("minute").asInt(),
            node.get("second").asInt(),
            node.get("nano").asInt(),
            zone
        )
    }

}
```

But is this ok? Or is there a better way to solve this?

**Comment by dkuc84** [comment]
Problem with custom scalars is that all your clients need to know how to correctly handle them - underneath it they are coerced to a String. If you configure your scalar in GraphQL schema (using your coercing logic from above) then GraphQL will take care of properly serializing/deserializing it on the server (you can try it out from the playground).

![Screen Shot 2019-06-10 at 8 59 07 AM](https://user-images.githubusercontent.com/9501705/59200535-15c61300-8b5e-11e9-994f-a5e714ebcecb.png)

I believe your problem was that you tried to use `ZonedDateTime` directly from a client? i.e. your client code needs to understand how to properly serialize and deserialize the objects. So while sending it as part of the query is simple -> if you pass `ZonedDateTime` object as variable it will default to `toString()` on it which matches your coercing logic. When you try to read it back though Jackson complains that it doesn't know how to convert the String to `ZonedDateTime` -> the default is to look for a default constructor and set the fields directly on the object (or look for annotated methods). Your custom deserializer is exactly how you can handle this.

**Comment by dkuc84** [comment]
Query used in the example above

```
fun modifyDateTimeQuery(dateTime: ZonedDateTime, days: Int): ZonedDateTime = dateTime.plusDays(days.toLong())
```

**Comment by dkuc84** [comment]
BTW you might also notice that results are incorrect in the above queries. Jackson by default tries to force the local time zones which leads to those invalid results. Fix is to add following to your Spring application configuration

```
    @Bean
    fun objectMapperCustomizer() = Jackson2ObjectMapperBuilderCustomizer { builder ->
        builder.featuresToDisable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
    }
```

**Comment by vetm73** [comment]
Tnx for your reply. It helped

Dit bericht is verzonden vanaf een mobiele telefoon
