### ISSUE TITLE
support data fetcher prefix annotation on Query/Mutation class

### ISSUE THREAD

**Issue by huangciyin** [ExpediaDotCom/graphql-kotlin#289]
1. support namespace through prefix on datafetcher/resolver function.

If we add an prefix annotation on Query/Mutation Class , all the data fetcher function in this class will be renamed by add the prefix, which can support namespace feature on graphql schema.
Example:
```
@GraphQLDataFetcherPrefix("example_prefix_")
class QueryObjectWithPrefix: Query {
   fun query1(value: Int) :Int{
        ...
    }

    fun query2(value: Int) :Int{
        ...
    }

    fun query3(value: Int) :Int{
        ...
    }
}
```
The above query would produce the following GraphQL schema:
```
schema {
  query: Query
}

type Query {
  example_prefix_query1(id: Int!): Int
  example_prefix_query2(id: Int!): Int
  example_prefix_query3(id: Int!): Int
}
```

2. we can use extends between Query/Mutation Class, avoid repeating the same code.
Example:
```
open class BaseQuery{
    open fun count(value: Int):String
    open fun find(value: Int):String
    open fun findById(value: Int):String
}

@GraphQLDataFetcherPrefix("book_")
class BookQuery: BaseQuery(),QueryResolver  

@GraphQLDataFetcherPrefix("user_")
class UserQuery: BaseQuery(),QueryResolver 
```

so we get the graphql schema like this: 

```
schema {
  query: Query
}

type Query {
    book_count(value: Int!):String
    book_find(value: Int!):String
    book_findById(value: Int!):String

    user_count(value: Int!):String
    user_find(value: Int!):String
    user_findById(value: Int!):String
}
```

implementation:  https://github.com/ExpediaDotCom/graphql-kotlin/pull/288

**Comment by smyrick** [comment]
@huangciyin In your interface example, instead of trying to have a top level field that represents somethings similar to REST you could have objects and interfaces

Like so

```kotlin
interface SearchableObject {
    fun count(value: Int): String
    fun find(value: Int): String
    fun findById(value: Int): String
}

class SearchBooks : SearchableObject {
    fun count(value: Int): String {
        // call the book API or DB to resolve info
    }
    // other functions ...
}

class SearchUsers : SearchableObject {
    fun count(value: Int): String {
        // call the user API or DB to resolve info
    }
    // other functions ...
}

class Query {
    fun books() = SearchBooks()
    fun users() = SearchUsers()
    fun findObject(value: Int): SearchableObject {
        // Search both users and books
    }
}
```


This would produce the following schema which has the same effect of "namespacing" your functions but doing in the type system so it can be better checked

```graphql
query NamespaceQuery {
    users {
        count
        find(value: 7)
    }
    findObject(value: 5) {
        ... on SearchUser {
            # Use aliases to create a custom name
            userCount: count
        }
        ... on SearchBook {
            # Use aliases to create a custom name
            bookCount: count
        }
    }
}
```

**Comment by smyrick** [comment]
From the PR: 

> @huangciyin Thank you for providing a contribution. It seems what you are trying to accomplish is change the name of the GraphQL fields from the Kotlin functions. We have an annotation today to already do this, `@GraphQLName`: https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Fields#documenting-fields
> 
> While this changes the entire name, and does not prepend a prefix like your changes, I don't see the need to include this feature. Ideally you shouldn't even need to use `@GraphQLName` as that is now changing the code from what developers see. If you want to have a naming convention, you can enforce that with code linters or just naming the functions that way.
> 
> We are going to close this PR. If you would like to start a discussion on a new feature request you can create a new issue with the feature tag: https://github.com/ExpediaDotCom/graphql-kotlin/issues/new/choose

**Comment by huangciyin** [comment]
@smyrick The Nested objects And Prefix are two way for Implementing Namespace, but they are different and not replaceable. 
I use Nested objects before, but then i find it's hard to find which top level fields are used in some middlewares such as gateway, for example: nginx log.  So I changed to use prefix.

**Comment by dkuc84** [comment]
@huangciyin as was already mentioned you already can implement namespacing by
- naming your functions in some pattern
- renaming the functions using `@GraphQLName` annotation
- introducing nested structure (as was nicely shown in the example above)
- use [SchemaGeneratorHooks](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt) to update your query/mutation/subscriptions (using corresponding `didGenerateXType`)

Since query classes generally won't (at least I hope they won't) hold hundreds of methods that would benefit from some common prefix in the graph, I personally don't see much value in adding this functionality over already existing alternatives.

**Comment by huangciyin** [comment]
@dkuc84 all the 4 method you list above can NOT use extends between query classes, see example in at https://github.com/ExpediaDotCom/graphql-kotlin/issues/289#issue-475974376 section 2.

**Comment by dkuc84** [comment]
@huangciyin unsure how your referenced example is supposed to work as it is using same method implementation for retrieving both book and user. If the intent was to define common interface then you could simply annotate the implementing methods OR restructure your queries to stronger types (see https://github.com/ExpediaDotCom/graphql-kotlin/issues/289#issuecomment-517768189)

**Comment by huangciyin** [comment]
implementation details like this:
```
@Component
open class BaseQuery{

    @GraphQLIgnore
    @Autowired
    lateinit var manager: BaseManager<T:BaseModel>

    open fun count(value: Int):String{
      return manager.count(value)
    }

    open fun find(value: Int):String{
      return manager.find(value)
    }

    open fun findById(value: Int):String{
      return manager.findById(value)
    }
}

@Component
@GraphQLDataFetcherPrefix("book_")
class BookQuery: BaseQuery(),QueryResolver 

@Component
@GraphQLDataFetcherPrefix("user_")
class UserQuery: BaseQuery(),QueryResolver
```

BookQuery  and UserQuery has different manager implementation, provided by IOC framework(spring).

**Comment by smyrick** [comment]
@huangciyin This seems like a very specific use case to how you want to construct your queries. While this would be a relatively small feature to implement, it would be one more feature that we would have to support for the library going forward that we don't think will get much use.

Because it is still a small feature to implement, once we fix this issue: https://github.com/ExpediaDotCom/graphql-kotlin/issues/294, you should be able to implement this logic yourself using your own annotations.

**Comment by smyrick** [comment]
Closing this as decided that we will not implement this feature as of now. If future use cases come up we can re-evaluate
